### ISSUE TITLE
Always the same error Fatal error: write EPIPE

### ISSUE THREAD

**Issue by nickjuntilla** [nathanpeck/exiftool#7]
Using Mac Yosemite and Node v0.10.26

**Comment by nathanpeck** [comment]
Do you have exiftool installed via homebrew and is it accessible on the command line?

Try this in your terminal to ensure that the exiftool binary is installed and accessible.

``` bash
which exiftool
```

**Comment by nickjuntilla** [comment]
Thanks for the fast response. Yes I should have read that more carefully, however I still haven't been able to get this working for my use case. 1 file works fine.  I have 857 files and I want to get the dimensions on each of them. It seems like every kind of asynchronous call I make fails either via promises or callbacks. Do you have any insight on this?

**Comment by barocsi** [comment]
Same for me, seems to happen when exifing large gifs

**Comment by jp-agustin** [comment]
Bump! I am also getting this same error.

> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
> Emitted 'error' event at:
>     at errorOrDestroy (internal/streams/destroy.js:107:12)
>     at onwriteError (_stream_writable.js:436:5)
>     at onwrite (_stream_writable.js:461:5)
>     at _destroy (internal/streams/destroy.js:49:7)
>     at Socket._destroy (net.js:613:3)
>     at Socket.destroy (internal/streams/destroy.js:37:8)
>     at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)

It works on images but error for some videos (not all). I tried using exiftool in terminal and it worked but not in node. Hopefully someone can help.

```
fs.readFile(Path.resolve(__dirname, file), (err, data) => {
  if (err) {
    throw err;
  } else {
    exif.metadata(data, (err, extractedMetadata) => {
      if (err) {
        console.log(err);
      }

      console.log(extractedMetadata);
    })
  }
})
```

**Comment by richiedevs** [comment]
same issue here aswell, using windows and latest Node LTS
